import Head from "next/head";
import Image from "next/image";
import MessageList from "../components/message-list/message-list.component";
import styles from "../styles/Home.module.css";
import convert from "xml-js";
import { useEffect, useState } from "react";
import Filter from "../components/filter/filter.component";

export default function Home() {
  const [messages, setMessages] = useState();
  const [filteredData, setFilteredData] = useState();
  useEffect(() => {
    fetch("api/hello").then((res) => {
      res
        .text()
        .then((data) => setMessages(JSON.parse(convert.xml2json(data))));
    });
  }, []);
  return (
    <div className={styles.main}>
      <div className={styles.mainHeading}>Голосовая почта</div>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {messages ? (
          <Filter messages={messages} setFilteredData={setFilteredData} />
        ) : (
          <h1>No data</h1>
        )}
        {filteredData ? <MessageList arr={filteredData} /> : <h1>No data</h1>}
      </div>
    </div>
  );
}
